# Generated by Django 5.2.5 on 2025-08-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers', 'Followers Only')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
